import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const file = fileURLToPath(new URL('../js/engine.js', import.meta.url));
const context = {window:{}};
if (fs.existsSync(file)) vm.runInNewContext(fs.readFileSync(file,'utf8'),context);
const E=context.window.AtlasEngine;
assert.ok(E, 'A real progress/review engine must be available');
const now=Date.UTC(2026,8,29,3), day=86400000;
const s=E.create();
assert.ok(E.validate(s));
assert.equal(Object.keys(s.lessons).length,0);
E.visit(s,120,'examples');
assert.equal(s.last.id,120);
assert.equal(s.last.anchor,'examples');
assert.equal(s.lessons[120].completedAt,0,'Opening is not completion');
E.complete(s,1,now);
assert.equal(s.lessons[1].due,now+day);
assert.equal(s.lessons[1].reviews,0,'Reading is not a successful recall');
E.complete(s,1,now+100);
assert.equal(s.lessons[1].due,now+day,'Re-reading must not postpone review');
E.review(s,1,true,now+1000);
assert.equal(s.lessons[1].due,now+day,'Early recall must not postpone future review');
E.review(s,1,true,now+day);
assert.equal(s.lessons[1].due,now+4*day);
assert.equal(s.lessons[1].interval,2);
E.review(s,1,true,now+day+1000);
assert.equal(s.lessons[1].due,now+4*day,'Repeated clicks must not inflate the interval');
E.review(s,1,false,now+4*day);
assert.equal(s.lessons[1].due,now+4*day+600000);
assert.equal(s.lessons[1].interval,0);
E.review(s,1,true,now+4*day+600000);
assert.equal(s.lessons[1].due,now+5*day+600000,'Short-interval recovery must move to tomorrow');
assert.equal(E.due(s,now+5*day).length,0);
assert.equal(E.due(s,now+6*day)[0],1);
assert.ok(E.validate(s));
for(const bad of [null,[],{version:1}, {...s,version:2},{...s,last:{id:121,anchor:'concept'}},{...s,lessons:{999:s.lessons[1]}},{...s,lessons:{1:{...s.lessons[1],due:-1}}},{...s,lessons:{1:{...s.lessons[1],note:'x'.repeat(20001)}}},{...s,lessons:{1:{...s.lessons[1],bookmarked:'yes'}}}]) assert.equal(E.validate(bad),false);
assert.throws(()=>E.visit(s,0));
assert.throws(()=>E.visit(s,121));
assert.throws(()=>E.review(s,2,true,now),'Unstarted lesson cannot enter a review schedule');
const serial=JSON.parse(JSON.stringify(s));
assert.ok(E.validate(serial),'Valid exported records must survive JSON');
assert.equal(E.matches({id:37,title:'의문사 who / what',summary:'어순'},'WHO'),true);
assert.equal(E.matches({id:37,title:'의문사',summary:'어순'},'37'),true);
assert.equal(E.matches({id:37,title:'의문사',summary:'어순'},'수동태'),false);
console.log('PASS: completion, due dates, early/double recall, failure/recovery, strict backup validation, source search');
